name: rsync
on:
  push:
    branches:
    - main
  pull_request:
    - main

jobs:
  deploy_job:
    name: Build and sync job
    runs-on: ubuntu-latest
    steps:
    - name: Cloning into repo
      uses: actions/checkout@v1
         
    - name: SSH setup
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
      run: |
        mkdir -p ~/.ssh
        echo "${KNOWN_HOSTS}" >> ~/.ssh/known_hosts
        echo "${DEPLOY_KEY}" > ~/.ssh/my_rsync_key
        echo "IdentityFile ~/.ssh/my_rsync_key" >> ~/.ssh/config
        chmod -R 700 ~/.ssh        
    - name: Rsync deployment
      run: |
                rsync -avz -e ssh --delete ${GITHUB_WORKSPACE}/ nitesh@20.197.1.204:~/atk-training-nitesh-fastpsq